Completed javascript-data-model exercise - Andrew Almeida
Andrew-M-A/c0522-code-solutions pull request #25
Opened 2022-05-17 20:08 UTC by Andrew-M-A

![javascript-data-model](https://user-images.githubusercontent.com/99862668/168900926-88192199-8911-487a-b43c-8e41bdb50761.png)

2022-05-17 22:26 UTC, codingcodymiller requested changes
Putting in a quick review so I know when you have sent your updates 🤓

2022-05-23 16:51 UTC, Andrew-M-A commented
![javascript-data-model](https://user-images.githubusercontent.com/99862668/169869460-0f68cdb9-16c3-48be-b525-ef129ae23a80.png)

2022-05-24 16:18 UTC, codingcodymiller requested changes

2022-05-25 16:24 UTC, codingcodymiller approved these changes
Nice work!

2022-05-25 20:13 UTC, merged